import { StyleSheet, Text, View } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 34,
    paddingBottom: 40,
    paddingHorizontal: 36,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: { textAlign: "center", marginBottom: 14 },
  companyName: { fontSize: 15, fontFamily: "Helvetica-Bold", marginBottom: 2 },
  subtitle: { fontSize: 10, color: "#4b4b4b" },
  divider: { borderBottom: "1pt solid #d0d0d0", marginTop: 8 },

  infoBlock: { paddingVertical: 10, marginBottom: 12 },
  infoRow: { flexDirection: "row", marginBottom: 5 },
  infoCol: { width: "50%", flexDirection: "row" },
  infoLabel: { color: "#666", width: 78 },
  infoValue: { fontFamily: "Helvetica-Bold" },

  sectionTitle: {
    fontSize: 9.5,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },

  footer: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    textAlign: "center",
    fontSize: 7.5,
    color: "#9a9a9a",
  },
});

export function formatInr(amount: number): string {
  return `Rs. ${new Intl.NumberFormat("en-IN", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(amount)}`;
}

interface PdfHeaderProps {
  companyName: string;
  subtitle: string;
}

export function PdfHeader({ companyName, subtitle }: PdfHeaderProps) {
  return (
    <View style={pdfStyles.header}>
      <Text style={pdfStyles.companyName}>{companyName}</Text>
      <Text style={pdfStyles.subtitle}>{subtitle}</Text>
      <View style={pdfStyles.divider} />
    </View>
  );
}

interface PdfEmployeeInfoProps {
  employeeName: string;
  designation: string;
  project: string;
  reportingFrom: string;
  reportingTo: string;
}

export function PdfEmployeeInfo({
  employeeName,
  designation,
  project,
  reportingFrom,
  reportingTo,
}: PdfEmployeeInfoProps) {
  return (
    <View style={pdfStyles.infoBlock}>
      <View style={pdfStyles.infoRow}>
        <View style={pdfStyles.infoCol}>
          <Text style={pdfStyles.infoLabel}>Employee Name</Text>
          <Text style={pdfStyles.infoValue}>{employeeName}</Text>
        </View>
        <View style={pdfStyles.infoCol}>
          <Text style={pdfStyles.infoLabel}>Designation</Text>
          <Text style={pdfStyles.infoValue}>{designation}</Text>
        </View>
      </View>
      <View style={pdfStyles.infoRow}>
        <View style={pdfStyles.infoCol}>
          <Text style={pdfStyles.infoLabel}>Project</Text>
          <Text style={pdfStyles.infoValue}>{project}</Text>
        </View>
        <View style={pdfStyles.infoCol}>
          <Text style={pdfStyles.infoLabel}>Reporting Period</Text>
          <Text style={pdfStyles.infoValue}>
            {reportingFrom} - {reportingTo}
          </Text>
        </View>
      </View>
    </View>
  );
}

export function PdfFooter({ companyName }: { companyName: string }) {
  return <Text style={pdfStyles.footer}>Generated by {companyName}</Text>;
}
